// Rehber: "Bilimsel çalışmak". Her bölüm FENER-PLAN.md bölüm 2'deki
// araştırmaya dayanır; evidence 1-3 arası kanıt gücünü (kaç nokta dolu) verir.
export const SECTIONS = [
  {
    id: 1,
    title: 'Bu rehber neden var: hisse değil ölçüme güveniyoruz',
    hook: 'Herkes sana bir çalışma yöntemi önerir. Bu rehber öneri değil, deney sonucu veriyor.',
    summary: "Buradaki her bölüm gerçek öğrencilerle yapılmış kontrollü deneylere dayanıyor, bazıları binlerce kişiyle. \"Böyle çalışırsan daha iyi olur\" değil, \"bunu deneyenler şu kadar fark yarattı\" diyoruz.",
    forYou: 'Bir yöntemi sana, sana benzeyen binlerce öğrenciye ne yaptığına bakarak seçtik.',
    appLink: null,
    evidence: null,
  },
  {
    id: 2,
    title: 'Beyin unutmak için tasarlandı',
    hook: 'Bugün öğrendiğin şeyin yarısını yarın bu saatte hatırlamıyor olacaksın. Bu bir başarısızlık değil.',
    summary: "1885'te Hermann Ebbinghaus kendi üzerinde deney yaptı ve öğrendiği listelerin yarısından fazlasını bir gün içinde unuttuğunu ölçtü. Ama her hatırlama denemesi bu unutmayı yavaşlatıyor.",
    forYou: 'Bir konuyu bir kez okuyup bırakmak, unutma eğrisine hiç dokunmuyor.',
    appLink: { route: '#/tekrar', label: 'Tekrar sekmesinde dene' },
    evidence: 3,
    diagram: 'forgetting-curve',
  },
  {
    id: 3,
    title: 'Aralıklı tekrar: 1 gün, 1 hafta, 1 ay',
    hook: 'Aynı soruyu art arda beş kez çözmek kolay hissettirir. Kolay hissettirmesi kötü haber.',
    summary: "Dunlosky ve ekibinin 2013'teki büyük incelemesi, onlarca yöntem arasında aralıklı tekrar ve kendini sınamayı en etkili iki teknik olarak buldu. Fener bu yüzden her soruyu 1, 7, 30 ve 90 gün sonra tekrar önüne getiriyor.",
    forYou: "Tekrar sekmesindeki \"sırası gelenler\" kartı, tam unutmaya başladığın anda karşına çıkacak şekilde ayarlı.",
    appLink: { route: '#/tekrar', label: 'Sırası gelenlere bak' },
    evidence: 3,
  },
  {
    id: 4,
    title: 'Karışık soru çözmek: %61’e karşı %37',
    hook: '20 soruluk bir seti hep aynı yöntemle çözmek rahatlatıcı. Sınavda işe yaramıyor.',
    summary: "Rohrer'in 2020'de 787 öğrenciyle yaptığı deneyde, konuları karıştırarak çalışan grup bir ay sonraki sınavda %61 aldı; aynı tipi art arda çözen grup %37 aldı. Eğitim araştırmalarında nadir görülen büyüklükte bir fark.",
    forYou: 'Matematik ve fen ağırlıklı bir programda bu, belki de tek başına en büyük kazanç.',
    appLink: null,
    evidence: 3,
    diagram: 'interleaving',
  },
  {
    id: 5,
    title: 'Fosforlu kalem neden işe yaramaz (ve neden bu uygulamanın rengi fosforlu sarı)',
    hook: "Altını çizdiğin sayfa sana \"öğrendim\" hissi veriyor. Hissettiğin şey öğrenme değil, tanıdıklık.",
    summary: "Aynı 2013 incelemesinde altını çizmek ve yeniden okumak, denenen on yöntem arasında en düşük fayda grubunda çıktı, çünkü pasif. Fener'in tek gösterişli rengi fosforlu sarı; ama süs değil, doldurduğun beher gibi gerçek bir ilerlemeyi gösteriyor.",
    forYou: 'Sarı burada "çalışıyormuş gibi görün" değil "gerçekten çalıştın" demek.',
    appLink: { route: '#/bugun', label: 'Beheri Bugün ekranında gör' },
    evidence: 3,
  },
  {
    id: 6,
    title: 'Odak: 25 dakika bir başlangıç, kural değil',
    hook: '25 dakika kutsal bir sayı değil. Bir yerden başlamak için iyi bir sayı.',
    summary: "Pomodoro üzerine yapılan yarı deneysel çalışmalarda odak %15-25 arttı, yorgunluk yaklaşık %20 azaldı. Ama 2025'teki bir karşılaştırma, katı 25/5 kuralının serbest ara verenlere göre motivasyonu daha hızlı düşürdüğünü buldu.",
    forYou: 'Süre sana uymuyorsa Ayarlar’dan değiştir; 25/5 bir emir değil, bir başlangıç noktası.',
    appLink: { route: '#/ayarlar', label: 'Süreni Ayarlar’dan değiştir' },
    evidence: 2,
  },
  {
    id: 7,
    title: 'Telefon masadayken bile dikkat çalıyor',
    hook: 'Telefonu sessize almak yetmiyor. Orada durması bile bir kısmını oradan alıyor.',
    summary: "Beyin ölçümlü deneylerde telefonun sadece görünür olması bile performansı düşürüyor; okullarda telefon yasakları katılımı artırdı. Norveç'te 9.846 ergenle yapılan çalışma, yatmadan önceki ekran süresinin uykuyu da kısalttığını gösterdi.",
    forYou: 'Oturuma başlarken "telefonu başka odaya bırak" uyarısı bu yüzden var, seni kontrol etmek için değil.',
    appLink: { route: '#/bugun', label: 'Odak oturumunu dene' },
    evidence: 3,
  },
  {
    id: 8,
    title: 'Dilek, sonuç, engel, plan: olumlu düşünmek yetmez',
    hook: '"Bu hafta çok çalışacağım" demek işe yaramıyor. Beynin buna inanıp rahatlıyor, sonra hiçbir şey değişmiyor.',
    summary: "Oettingen ve Duckworth'ün okul çocuklarıyla yaptığı deneylerde, yalnızca olumlu düşünmek yerine dilek-sonuç-engel-plan sırasını izleyenlerin notları, devamları ve davranışları belirgin iyileşti. \"Eğer X olursa, o zaman Y yapacağım\" cümlesi tek başına en güçlü araç.",
    forYou: 'Hafta sekmesindeki plan sihirbazı tam olarak bu dört adımı soruyor, sırayla.',
    appLink: { route: '#/hafta', label: 'Bu haftanın planını yap' },
    evidence: 3,
  },
  {
    id: 9,
    title: 'Zorlanmak beynin büyüdüğünün işareti, ama abartmadan',
    hook: 'Bir soruda takılmak "yetersizim" demek değil. Ama bu cümleyi söylemek tek başına seni bir yere götürmüyor.',
    summary: "Yeager'ın 2019'da Nature'da yayımlanan, 12.500 dokuzuncu sınıf öğrencisiyle yaptığı deneyde, kısa büyüme zihniyeti mesajları düşük başarılı öğrencilerin notunu 0,10 puan artırdı, küçük ama gerçek bir etki.",
    forYou: 'Fen lisesindeysen zaten yüksek başarılısın; bu fikir ana çözümün değil, zor bir günde hatırlaman gereken bir cümle.',
    appLink: null,
    evidence: 2,
  },
  {
    id: 10,
    title: 'Uyku: 8–10 saat, çünkü öğrenme uykuda tamamlanır',
    hook: 'Gece geç saate kadar çalışmak fedakarlık gibi hissettiriyor. Genelde tam tersi oluyor.',
    summary: "Amerikan Uyku Tıbbı Akademisi 13-18 yaş için günde 8-10 saat uyku öneriyor. Norveç'te 9.846 ergenle yapılan çalışmada, yatmadan önceki ekran süresi uykuya dalmayı geciktirip toplam uykuyu kısaltıyordu.",
    forYou: 'Fener saat 22:30’dan sonra yeni oturum açmıyor; bu tembellik değil, ertesi gün daha iyi çalışman için.',
    appLink: { route: '#/ayarlar', label: 'Yatma saatini ayarla' },
    evidence: 3,
  },
  {
    id: 11,
    title: 'Bu uygulamada neden puan, rozet ve seri sayacı yok',
    hook: '47 gün üst üste kullandığını gösteren bir sayaç kulağa iyi geliyor. Bir gün kaçırdığında seni tamamen bırakmaya itiyor.',
    summary: "Öz-belirleme kuramı araştırmaları, ödül ve puanın kontrol amaçlı kullanıldığında içsel ilgiyi zayıflattığını gösteriyor; oyunlaştırmanın 35 deneyi birleştiren incelemesinde toplam etki küçük çıktı.",
    forYou: 'Burada haftalık esnek hedef var: 7 günden 5’i yeter, kaçırdığın gün ceza değil.',
    appLink: { route: '#/bugun', label: 'Haftalık hedef çizgine bak' },
    evidence: 2,
  },
  {
    id: 12,
    title: 'Küçük başla: bir soru bile sayılır',
    hook: '"Bugün 3 saat çalışacağım" demek çoğu zaman hiç başlamamakla bitiyor.',
    summary: "BJ Fogg'un Küçük Alışkanlıklar yöntemine göre motivasyon dalgalıdır, ona güvenilmez; alışkanlığı motivasyon düşükken bile yapılacak kadar küçültmek gerekir. Küçük başlayanların alışkanlığı sürdürme olasılığı bir çalışmada 2,7 kat fazla çıktı.",
    forYou: 'Bugünün 3 işinden biri "bir soru çöz" olabilir, bu az değil, bu yeterli.',
    appLink: { route: '#/bugun', label: 'Bugünün işlerini aç' },
    evidence: 2,
  },
  {
    id: 13,
    title: 'Kaynaklar',
    hook: 'Merak ettiysen, hepsi burada.',
    summary: 'Bu rehberdeki her iddia gerçek bir araştırmaya dayanıyor. Ayrıntılı kaynak listesi FENER-PLAN.md içinde.',
    forYou: '',
    appLink: null,
    evidence: null,
    sources: [
      'Dunlosky ve ark. 2013, Improving Students’ Learning With Effective Learning Techniques',
      'Rohrer ve ark. 2020, A Randomized Controlled Trial of Interleaved Mathematics Practice',
      'Duckworth, Kirby, Gollwitzer, Oettingen 2013, Mental Contrasting with Implementation Intentions',
      'Yeager ve ark. 2019, A national experiment reveals where a growth mindset improves achievement, Nature',
      'AASM ergen uyku önerisi',
      'Telefon varlığı ve dikkat, EEG çalışması',
      'Guay 2022, Öz-belirleme kuramı ve eğitim',
      'BJ Fogg Küçük Alışkanlıklar, NPR 2026',
    ],
  },
];

export function findSection(id) {
  return SECTIONS.find(s => s.id === Number(id));
}
